### ISSUE TITLE
UI elements

### ISSUE THREAD

**Issue by salmonling** [TOTKSheet/TOTKImages#1]
I hope this isn't a bother but I couldn't find any other way to contact you; anyway are you planning on uploading any ui assets? specifically stuff from the purah pad & hyrule compendium. No worries if not, just thought I'd ask since i've been looking for them

Thanks for doing all this by the way! Feel free to delete this post if you don't want it on your page. Or ask me to do it if you can't IDK how this site works

**Comment by phil-macrocheira** [comment]
If you're still looking for these assets, we can probably help you over at the TOTK Datamining discord server

https://discord.gg/9EYxbXsu

**Comment by salmonling** [comment]
okay thank you!
